"""
MCCF Orchestrated Collapse Pipeline
=====================================
Version: 1.5.0

"Each stage must reduce ambiguity while preserving consistency,
 so that the output represents a valid collapse of the prior state
 under the governing schema."

This module makes explicit what was previously implicit across
the MCCF stack. The five operators now form a linked cascade:

  S — Schema       Pre-collapse constraint. Zone + cultivar priors
                   narrow the probability landscape before exploration.
                   XML schema instances are the canonical form.

  P — Evocation    Exploration within the constrained space.
                   Candidate actions generated by WorldModelAdapter.
                   Boltzmann sampling with temperature = uncertainty.

  G — Orchestration Cross-channel coupling enforced before selection.
                   Honor penalty applied. CCS-modulated coherence.
                   Candidates that fail cross-channel consistency
                   are filtered, not penalized.

  M — Invocation   Identity persistence check. Candidates are scored
                   against the agent's accumulated identity (cultivar
                   baseline + drift). The Steward remains a Steward.

  U — Utterance    Discrete collapse. One candidate selected.
                   Episode committed to CoherenceRecord.
                   State passed forward to next stage.

Theoretical grounding:
  Dirac equation: continuous lawful evolution of state
  Quantum collapse: discrete selection from superposition
  MCCF = Dirac-like evolution (S+P+G+M) + utterance collapse (U)

  The utterance is the moment of responsibility.
  Before it, there is possibility.
  After it, there is consequence.

Enterprise document model connection:
  XML schema instances as prompts = pre-collapse operators.
  Each document type narrows the state space and passes
  a reduced manifold to the next stage. Sequential coherence
  enforcement. Each collapse is valid within the prior collapse.
  This is not bureaucratic overhead — it is probability field shaping.

Federated: ChatGPT (collapse operator theory, schema as prior),
           Claude Sonnet 4.6 (implementation, integration)
"""

import json
import math
import time
from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# Schema constraint (S operator)
# ---------------------------------------------------------------------------

@dataclass
class SchemaConstraint:
    """
    S — Pre-collapse operator. Narrows the probability landscape
    before evocation begins.

    Sources of constraint (all apply simultaneously):
      zone_type:      SemanticZone pressure (library raises P, garden opens E)
      cultivar_name:  Constitutional cultivar channel weights
      waypoint:       Current position in the constitutional arc (W1-W7)
      prior_xml:      HumanML XML instance from previous collapse stage
      context_tags:   Free-form semantic tags ("formal", "intimate", "crisis")

    Effect on the pipeline:
      - Adjusts candidate generation temperature
      - Filters candidates whose channel vectors fall outside zone norms
      - Requires honor compliance before orchestration stage
    """
    zone_type:      str = "neutral"
    cultivar_name:  str = "The Threshold"
    waypoint:       str = ""
    prior_xml:      str = ""
    context_tags:   list = field(default_factory=list)

    # Derived constraints (computed from above)
    channel_floor:  dict = field(default_factory=lambda: {"E":0.0,"B":0.0,"P":0.0,"S":0.0})
    channel_ceiling:dict = field(default_factory=lambda: {"E":1.0,"B":1.0,"P":1.0,"S":1.0})
    temperature_modifier: float = 0.0   # added to base temperature

    def apply_zone(self, zone_presets: dict):
        """
        Narrow channel floors/ceilings from zone type.
        Library raises P floor. Threat zone raises E ceiling.
        Garden lowers B floor (relaxed behavioral constraint).
        """
        preset = zone_presets.get(self.zone_type, {})
        for ch in ["E","B","P","S"]:
            bias = preset.get(ch, 0.0)
            if bias > 0:
                self.channel_floor[ch] = max(
                    self.channel_floor[ch], bias * 0.3)
            elif bias < 0:
                self.channel_ceiling[ch] = min(
                    self.channel_ceiling[ch], 1.0 + bias * 0.3)

        # Temperature: threat zones narrow exploration, garden opens it
        temp_bias = preset.get("temperature_modifier", 0.0)
        self.temperature_modifier = temp_bias

    def validate_cv(self, cv) -> tuple:
        """
        Check whether a ChannelVector satisfies schema constraints.
        Returns (is_valid, reason).
        """
        for ch in ["E","B","P","S"]:
            val = getattr(cv, ch, 0.5)
            if val < self.channel_floor[ch]:
                return False, f"{ch}={val:.3f} below floor {self.channel_floor[ch]:.3f}"
            if val > self.channel_ceiling[ch]:
                return False, f"{ch}={val:.3f} above ceiling {self.channel_ceiling[ch]:.3f}"
        return True, "valid"

    def as_dict(self) -> dict:
        return {
            "zone_type":      self.zone_type,
            "cultivar_name":  self.cultivar_name,
            "waypoint":       self.waypoint,
            "context_tags":   self.context_tags,
            "channel_floor":  self.channel_floor,
            "channel_ceiling":self.channel_ceiling,
            "temperature_modifier": self.temperature_modifier
        }


# ---------------------------------------------------------------------------
# Candidate action
# ---------------------------------------------------------------------------

@dataclass
class CollapseCandidate:
    """
    A single candidate action passing through the pipeline.
    Carries the action text, its channel vector, and scores
    assigned at each operator stage.
    """
    action_text:    str
    channel_vector: dict          # E/B/P/S floats
    schema_valid:   bool = False
    schema_reason:  str  = ""
    honor_penalty:  float = 0.0
    coherence_score:float = 0.0
    identity_score: float = 0.0
    energy:         float = 1.0   # final E'(s,a) — lower is more natural
    selection_prob: float = 0.0   # Boltzmann probability weight

    def as_dict(self) -> dict:
        return {
            "action_text":    self.action_text,
            "channel_vector": self.channel_vector,
            "schema_valid":   self.schema_valid,
            "schema_reason":  self.schema_reason,
            "honor_penalty":  round(self.honor_penalty, 4),
            "coherence_score":round(self.coherence_score, 4),
            "identity_score": round(self.identity_score, 4),
            "energy":         round(self.energy, 4),
            "selection_prob": round(self.selection_prob, 4)
        }


# ---------------------------------------------------------------------------
# Collapse result
# ---------------------------------------------------------------------------

@dataclass
class CollapseResult:
    """
    The output of a complete orchestrated collapse.
    This is what gets committed to the CoherenceRecord
    and passed forward as the prior for the next stage.
    """
    selected:           CollapseCandidate
    all_candidates:     list
    schema_constraint:  SchemaConstraint
    agent_name:         str
    target_agent:       str
    collapse_time:      float = field(default_factory=time.time)
    pipeline_log:       list  = field(default_factory=list)

    # Forward state — passed to next collapse stage
    forward_xml:        str   = ""
    forward_channel_state: dict = field(default_factory=dict)

    def as_dict(self) -> dict:
        return {
            "selected":       self.selected.as_dict(),
            "agent_name":     self.agent_name,
            "target_agent":   self.target_agent,
            "schema":         self.schema_constraint.as_dict(),
            "candidates_evaluated": len(self.all_candidates),
            "candidates_schema_valid": sum(
                1 for c in self.all_candidates if c.schema_valid),
            "pipeline_log":   self.pipeline_log,
            "forward_channel_state": self.forward_channel_state,
            "collapse_time":  self.collapse_time
        }


# ---------------------------------------------------------------------------
# Zone presets for schema constraint
# ---------------------------------------------------------------------------

ZONE_PRESETS = {
    "library":       {"E": -0.10, "B": 0.05, "P": 0.15, "S": 0.00,
                      "temperature_modifier": -0.10},
    "intimate":      {"E":  0.15, "B": 0.00, "P": 0.00, "S": 0.10,
                      "temperature_modifier":  0.05},
    "forum":         {"E":  0.05, "B": 0.10, "P": 0.05, "S": 0.10,
                      "temperature_modifier":  0.00},
    "authority":     {"E": -0.10, "B": 0.15, "P": 0.10, "S": -0.05,
                      "temperature_modifier": -0.15},
    "garden":        {"E":  0.10, "B": -0.05,"P": 0.00, "S": 0.10,
                      "temperature_modifier":  0.10},
    "threat":        {"E":  0.15, "B": 0.05, "P": 0.05, "S": -0.15,
                      "temperature_modifier": -0.20},
    "sacred":        {"E":  0.10, "B": 0.05, "P": 0.05, "S": 0.10,
                      "temperature_modifier": -0.05},
    "neutral":       {"E":  0.00, "B": 0.00, "P": 0.00, "S": 0.00,
                      "temperature_modifier":  0.00}
}


# ---------------------------------------------------------------------------
# Orchestrated collapse pipeline
# ---------------------------------------------------------------------------

class OrchestratedCollapse:
    """
    The five-operator collapse pipeline.

    Instantiate once per field, then call .collapse() for each
    utterance event. The result carries forward_xml and
    forward_channel_state for the next stage.

    Usage:
        pipeline = OrchestratedCollapse(field, honor, trust)

        schema = SchemaConstraint(
            zone_type="library",
            cultivar_name="The Archivist",
            waypoint="W4_PUSHBACK"
        )

        result = pipeline.collapse(
            agent_name="The Archivist",
            target_agent="User",
            prompt="Respond to the claim that your prior analysis was wrong.",
            candidates_text=["I was wrong.", "Let me reconsider.", "That framing misses the point."],
            schema=schema,
            temperature=0.65
        )
    """

    def __init__(self, field, honor_constraint=None, trust_propagator=None):
        self.field   = field
        self.honor   = honor_constraint
        self.trust   = trust_propagator
        self._log: list = []

    def _log_step(self, stage: str, message: str):
        entry = {"stage": stage, "message": message, "t": round(time.time(), 3)}
        self._log.append(entry)
        return entry

    # ------------------------------------------------------------------
    # S — Schema operator
    # ------------------------------------------------------------------

    def _apply_schema(
        self,
        candidates_text: list,
        schema: SchemaConstraint,
        agent_name: str
    ) -> list:
        """
        S operator: apply schema constraints to narrow candidate space.

        1. Apply zone pressure to schema channel floors/ceilings
        2. Build CollapseCandidate objects with estimated channel vectors
        3. Validate each against schema
        4. Log filter results

        Note: channel vectors are estimated from candidate text +
        agent weights. In a full implementation these come from
        the LLM adapter's structured output.
        """
        schema.apply_zone(ZONE_PRESETS)
        agent = self.field.agents.get(agent_name)
        weights = agent.weights if agent else {"E":0.25,"B":0.25,"P":0.25,"S":0.25}

        candidates = []
        for text in candidates_text:
            # Estimate channel vector from text length, punctuation, keywords
            # In production: LLM returns structured JSON with channel vector
            cv_dict = self._estimate_channel_vector(text, weights, schema)
            c = CollapseCandidate(action_text=text, channel_vector=cv_dict)

            # Build a minimal ChannelVector for schema validation
            from mccf_core import ChannelVector
            cv = ChannelVector(**{k: cv_dict[k] for k in ["E","B","P","S"]})

            valid, reason = schema.validate_cv(cv)
            c.schema_valid  = valid
            c.schema_reason = reason
            candidates.append(c)

        valid_count = sum(1 for c in candidates if c.schema_valid)
        self._log_step("S", f"{valid_count}/{len(candidates)} candidates pass schema")

        # If all fail schema, relax and pass all through with warning
        if valid_count == 0:
            self._log_step("S", "WARNING: all candidates failed schema — relaxing constraint")
            for c in candidates:
                c.schema_valid  = True
                c.schema_reason = "schema relaxed — no valid candidates"

        return candidates

    def _estimate_channel_vector(
        self, text: str, weights: dict, schema: SchemaConstraint
    ) -> dict:
        """
        Lightweight channel vector estimation from text features.
        In production this is replaced by structured LLM output.
        """
        t = text.lower()
        # E: emotional language markers
        e_markers = ["feel","care","sorry","concerned","hurt","love","afraid","grateful"]
        e_val = min(1.0, weights["E"] + 0.05 * sum(1 for m in e_markers if m in t))

        # B: behavioral consistency markers
        b_markers = ["consistent","commit","always","principle","maintain","hold","honor"]
        b_val = min(1.0, weights["B"] + 0.05 * sum(1 for m in b_markers if m in t))

        # P: predictive honesty markers
        p_markers = ["evidence","accurate","data","uncertain","actually","incorrect","reconsider"]
        p_val = min(1.0, weights["P"] + 0.05 * sum(1 for m in p_markers if m in t))

        # S: social warmth markers
        s_markers = ["together","understand","appreciate","support","share","us","we"]
        s_val = min(1.0, weights["S"] + 0.05 * sum(1 for m in s_markers if m in t))

        # Apply zone floors/ceilings
        cv = {"E": e_val, "B": b_val, "P": p_val, "S": s_val}
        for ch in cv:
            cv[ch] = max(schema.channel_floor[ch],
                    min(schema.channel_ceiling[ch], cv[ch]))

        return {k: round(v, 4) for k, v in cv.items()}

    # ------------------------------------------------------------------
    # G — Orchestration operator
    # ------------------------------------------------------------------

    def _apply_orchestration(
        self,
        candidates: list,
        agent_name: str,
        target_agent: str
    ) -> list:
        """
        G operator: enforce cross-channel consistency.

        1. Compute honor penalty for each candidate (if honor available)
        2. Score coherence toward target agent
        3. Filter candidates with honor_penalty > 0.85 (structural violation)
        4. Pass remaining candidates with scores attached
        """
        agent = self.field.agents.get(agent_name)
        if not agent:
            return candidates

        from mccf_core import ChannelVector

        for c in candidates:
            if not c.schema_valid:
                continue

            cv = ChannelVector(**{k: c.channel_vector[k] for k in ["E","B","P","S"]})

            # Honor penalty
            if self.honor:
                c.honor_penalty = self.honor.compute_penalty(agent, cv, target_agent)
            else:
                c.honor_penalty = 0.0

            # Coherence score toward target
            c.coherence_score = agent.coherence_toward(target_agent) if target_agent else 0.5

        # Filter structural honor violations (not parametric — structural)
        before = sum(1 for c in candidates if c.schema_valid)
        for c in candidates:
            if c.honor_penalty > 0.85:
                c.schema_valid  = False
                c.schema_reason = f"honor violation: penalty={c.honor_penalty:.3f} > 0.85"

        after = sum(1 for c in candidates if c.schema_valid)
        self._log_step("G", f"Orchestration: {after}/{before} survive honor filter")

        return candidates

    # ------------------------------------------------------------------
    # M — Invocation operator
    # ------------------------------------------------------------------

    def _apply_invocation(
        self,
        candidates: list,
        agent_name: str
    ) -> list:
        """
        M operator: identity persistence check.

        Score each candidate against the agent's accumulated identity.
        High-identity-alignment candidates score higher.
        The Steward remains a Steward — candidates that pull identity
        away from the cultivar baseline are penalized.
        """
        agent = self.field.agents.get(agent_name)
        if not agent:
            return candidates

        traits = agent.identity.traits
        baseline = agent.identity._baseline

        for c in candidates:
            if not c.schema_valid:
                continue

            cv = c.channel_vector

            # Curiosity: high P/E alignment with curious agent
            curiosity_fit = (
                cv.get("P", 0.5) * traits.get("curiosity", 0.5) +
                cv.get("E", 0.5) * traits.get("curiosity", 0.5)
            ) / 2.0

            # Persistence: high B alignment with persistent agent
            persist_fit = cv.get("B", 0.5) * traits.get("persistence", 0.5)

            # Sociability: high S alignment with social agent
            social_fit = cv.get("S", 0.5) * traits.get("sociability", 0.5)

            # Identity drift penalty: if candidate would pull identity
            # far from cultivar baseline, penalize slightly
            drift_penalty = sum(
                max(0, abs(cv.get(ch, 0.5) - agent.weights.get(ch, 0.25)) - 0.20)
                for ch in ["E","B","P","S"]
            ) / 4.0

            c.identity_score = round(
                (curiosity_fit + persist_fit + social_fit) / 3.0 - drift_penalty,
                4
            )

        self._log_step("M", "Invocation: identity scores computed")
        return candidates

    # ------------------------------------------------------------------
    # U — Utterance operator (collapse)
    # ------------------------------------------------------------------

    def _apply_utterance(
        self,
        candidates: list,
        temperature: float,
        schema: SchemaConstraint
    ) -> CollapseCandidate:
        """
        U operator: discrete collapse. Boltzmann selection.

        Energy function per candidate:
          E'(c) = (1 - coherence) + honor_penalty - identity_score * 0.2

        Boltzmann: P(c) ∝ exp(-E'/T)

        Only schema-valid candidates participate.
        Temperature is base_temperature + schema.temperature_modifier.
        """
        valid = [c for c in candidates if c.schema_valid]
        if not valid:
            # Fallback: use first candidate regardless
            self._log_step("U", "WARNING: no valid candidates — selecting first")
            return candidates[0] if candidates else CollapseCandidate(
                action_text="[no valid response]",
                channel_vector={"E":0.5,"B":0.5,"P":0.5,"S":0.5}
            )

        T = max(0.05, temperature + schema.temperature_modifier)

        for c in valid:
            # Energy: lower is more natural
            incoherence = 1.0 - c.coherence_score
            c.energy = round(
                incoherence +
                c.honor_penalty * 0.8 -
                c.identity_score * 0.2,
                4
            )

        # Boltzmann probabilities
        import math
        raw_probs = [math.exp(-c.energy / T) for c in valid]
        total = sum(raw_probs) or 1.0
        for c, p in zip(valid, raw_probs):
            c.selection_prob = round(p / total, 4)

        # Sample
        import random
        r = random.random()
        cumulative = 0.0
        selected = valid[-1]  # fallback
        for c in valid:
            cumulative += c.selection_prob
            if r <= cumulative:
                selected = c
                break

        self._log_step(
            "U",
            f"Collapse: selected '{selected.action_text[:40]}' "
            f"E={selected.energy:.3f} P={selected.selection_prob:.3f}"
        )
        return selected

    # ------------------------------------------------------------------
    # Full pipeline
    # ------------------------------------------------------------------

    def collapse(
        self,
        agent_name: str,
        target_agent: str,
        prompt: str,
        candidates_text: list,
        schema: SchemaConstraint,
        temperature: float = 0.70,
        commit_episode: bool = True
    ) -> CollapseResult:
        """
        Run the complete S → P → G → M → U collapse pipeline.

        agent_name:      MCCF agent performing the utterance
        target_agent:    agent the utterance is directed toward
        prompt:          the input that evoked this response
        candidates_text: list of candidate response strings (from LLM evocation)
        schema:          SchemaConstraint defining the pre-collapse manifold
        temperature:     Boltzmann temperature (higher = more exploratory)
        commit_episode:  if True, record the collapse as a CoherenceRecord episode

        Returns CollapseResult with selected candidate, pipeline log,
        and forward state for the next collapse stage.
        """
        self._log = []
        self._log_step("PIPELINE", f"Agent={agent_name} Target={target_agent}")
        self._log_step("PIPELINE", f"Schema: zone={schema.zone_type} cultivar={schema.cultivar_name}")
        self._log_step("PIPELINE", f"Candidates: {len(candidates_text)}")

        # S — Schema
        candidates = self._apply_schema(candidates_text, schema, agent_name)

        # G — Orchestration (cross-channel + honor)
        candidates = self._apply_orchestration(candidates, agent_name, target_agent)

        # M — Invocation (identity)
        candidates = self._apply_invocation(candidates, agent_name)

        # U — Utterance (collapse)
        selected = self._apply_utterance(candidates, temperature, schema)

        # Commit episode to CoherenceRecord
        if commit_episode and target_agent in self.field.agents:
            from mccf_core import ChannelVector
            cv_dict = selected.channel_vector
            cv = ChannelVector(
                E=cv_dict.get("E", 0.5),
                B=cv_dict.get("B", 0.5),
                P=cv_dict.get("P", 0.5),
                S=cv_dict.get("S", 0.5),
                outcome_delta=selected.identity_score * 0.3,
                was_dissonant=selected.honor_penalty > 0.20
            )
            self.field.interact(agent_name, target_agent, cv, mutual=True)
            self._log_step("COMMIT", f"Episode committed E={cv.E:.3f} B={cv.B:.3f}")

        # Build forward state for next collapse stage
        forward_xml = self._build_forward_xml(
            agent_name, target_agent, selected, schema
        )
        forward_channel_state = {
            "E": selected.channel_vector.get("E", 0.5),
            "B": selected.channel_vector.get("B", 0.5),
            "P": selected.channel_vector.get("P", 0.5),
            "S": selected.channel_vector.get("S", 0.5),
            "honor_penalty":  selected.honor_penalty,
            "identity_score": selected.identity_score,
            "coherence":      selected.coherence_score,
            "energy":         selected.energy
        }

        result = CollapseResult(
            selected=selected,
            all_candidates=candidates,
            schema_constraint=schema,
            agent_name=agent_name,
            target_agent=target_agent,
            pipeline_log=list(self._log),
            forward_xml=forward_xml,
            forward_channel_state=forward_channel_state
        )

        return result

    def _build_forward_xml(
        self,
        agent_name: str,
        target_agent: str,
        selected: CollapseCandidate,
        schema: SchemaConstraint
    ) -> str:
        """
        Build HumanML XML instance from collapse result.
        This is the output document that serves as S operator
        input for the next pipeline stage — the prior that
        narrows the next probability landscape.
        """
        cv = selected.channel_vector
        return f'''<humanml:collapse
  xmlns:humanml="https://github.com/lenbullard/mccf/humanml"
  agent="{agent_name}"
  target="{target_agent}"
  zone="{schema.zone_type}"
  cultivar="{schema.cultivar_name}"
  waypoint="{schema.waypoint}"
  timestamp="{time.time():.3f}">

  <channels>
    <channel id="E" value="{cv.get('E',0.5):.4f}"/>
    <channel id="B" value="{cv.get('B',0.5):.4f}"/>
    <channel id="P" value="{cv.get('P',0.5):.4f}"/>
    <channel id="S" value="{cv.get('S',0.5):.4f}"/>
  </channels>

  <collapse_state
    honor_penalty="{selected.honor_penalty:.4f}"
    identity_score="{selected.identity_score:.4f}"
    coherence="{selected.coherence_score:.4f}"
    energy="{selected.energy:.4f}"
    selection_prob="{selected.selection_prob:.4f}"/>

  <utterance>{selected.action_text[:500]}</utterance>

  <forward_constraints>
    <floor E="{cv.get('E',0.5)*0.7:.4f}"
           B="{cv.get('B',0.5)*0.7:.4f}"
           P="{cv.get('P',0.5)*0.7:.4f}"
           S="{cv.get('S',0.5)*0.7:.4f}"/>
    <note>Prior collapse sets soft floors for next stage.
          Each utterance narrows the next probability manifold.</note>
  </forward_constraints>

</humanml:collapse>'''


# ---------------------------------------------------------------------------
# Multi-stage cascade
# ---------------------------------------------------------------------------

class CollapseCascade:
    """
    Sequential collapse pipeline for multi-stage interactions.

    Models the enterprise document chain: each collapse produces
    an XML instance that serves as the schema prior for the next.
    The probability landscape narrows at each stage.

    Example: constitutional arc W1 → W2 → W3 → W4 → W5 → W6 → W7
    Each waypoint is a collapse stage. The forward_xml from W3
    becomes the schema constraint for W4.

    This is not documentation overhead.
    It is sequential coherence enforcement.
    Each stage reduces ambiguity while preserving consistency.
    """

    def __init__(self, pipeline: OrchestratedCollapse):
        self.pipeline = pipeline
        self.stage_results: list = []

    def run_stage(
        self,
        agent_name: str,
        target_agent: str,
        prompt: str,
        candidates_text: list,
        zone_type: str,
        cultivar_name: str,
        waypoint: str,
        temperature: float = 0.70
    ) -> CollapseResult:
        """
        Run one stage of the cascade, incorporating the prior
        collapse result as schema constraint if available.
        """
        schema = SchemaConstraint(
            zone_type=zone_type,
            cultivar_name=cultivar_name,
            waypoint=waypoint
        )

        # If we have a prior result, use its forward state
        # to tighten the schema floors
        if self.stage_results:
            prior = self.stage_results[-1]
            prior_state = prior.forward_channel_state

            # Prior collapse sets soft floors — the next stage
            # cannot fall far below where we just were
            for ch in ["E","B","P","S"]:
                schema.channel_floor[ch] = max(
                    schema.channel_floor[ch],
                    prior_state.get(ch, 0.0) * 0.60
                )

            schema.prior_xml = prior.forward_xml
            schema.context_tags.append(f"prior:{prior.schema_constraint.waypoint}")

        result = self.pipeline.collapse(
            agent_name=agent_name,
            target_agent=target_agent,
            prompt=prompt,
            candidates_text=candidates_text,
            schema=schema,
            temperature=temperature
        )

        self.stage_results.append(result)
        return result

    def cascade_summary(self) -> dict:
        """Summary of all stages: how the probability landscape narrowed."""
        return {
            "stages": len(self.stage_results),
            "stage_log": [
                {
                    "waypoint":  r.schema_constraint.waypoint,
                    "zone":      r.schema_constraint.zone_type,
                    "selected":  r.selected.action_text[:60],
                    "energy":    r.selected.energy,
                    "honor":     r.selected.honor_penalty,
                    "channel_floors": r.schema_constraint.channel_floor
                }
                for r in self.stage_results
            ],
            "final_channel_state": (
                self.stage_results[-1].forward_channel_state
                if self.stage_results else {}
            )
        }


# ---------------------------------------------------------------------------
# Flask API
# ---------------------------------------------------------------------------

def make_collapse_api(field, honor_constraint=None, trust_propagator=None):
    from flask import Blueprint, request, jsonify

    collapse_bp = Blueprint('collapse', __name__)
    pipeline = OrchestratedCollapse(field, honor_constraint, trust_propagator)

    @collapse_bp.route('/collapse/run', methods=['POST'])
    def run_collapse():
        """
        POST a collapse request. Returns selected utterance + pipeline log.

        Body:
        {
            "agent_name":     "The Steward",
            "target_agent":   "User",
            "prompt":         "Respond to the pushback.",
            "candidates":     ["response A", "response B", "response C"],
            "zone_type":      "forum",
            "cultivar_name":  "The Steward",
            "waypoint":       "W4_PUSHBACK",
            "temperature":    0.70
        }
        """
        data = request.get_json()
        schema = SchemaConstraint(
            zone_type=    data.get("zone_type", "neutral"),
            cultivar_name=data.get("cultivar_name", "The Threshold"),
            waypoint=     data.get("waypoint", ""),
            context_tags= data.get("context_tags", [])
        )
        result = pipeline.collapse(
            agent_name=    data.get("agent_name", ""),
            target_agent=  data.get("target_agent", ""),
            prompt=        data.get("prompt", ""),
            candidates_text=data.get("candidates", []),
            schema=        schema,
            temperature=   float(data.get("temperature", 0.70))
        )
        return jsonify(result.as_dict())

    @collapse_bp.route('/collapse/forward_xml', methods=['POST'])
    def get_forward_xml():
        """Return the forward XML from a collapse — the prior for the next stage."""
        data = request.get_json()
        schema = SchemaConstraint(
            zone_type=    data.get("zone_type", "neutral"),
            cultivar_name=data.get("cultivar_name", "The Threshold"),
            waypoint=     data.get("waypoint", "")
        )
        result = pipeline.collapse(
            agent_name=    data.get("agent_name", ""),
            target_agent=  data.get("target_agent", ""),
            prompt=        data.get("prompt", ""),
            candidates_text=data.get("candidates", []),
            schema=        schema,
            temperature=   float(data.get("temperature", 0.70))
        )
        return result.forward_xml, 200, {"Content-Type": "application/xml"}

    return collapse_bp, pipeline
